build (Ubuntu 19.04):
    stage: build
    image: ubuntu:19.04
    before_script:
        - apt-get update
        - apt-get install -y g++ cmake libsqlite3-dev qt5-default
            libboost-signals-dev cppcheck
    script:
        - cmake .
        - cmake --build . -- -j4
